---
- hosts: vagrant
  remote_user: vagrant
  roles:
  - base

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  vars:
    rvm1_rubies:
    - 'ruby-2.0.0'
    rvm1_rvm_version: 'stable'
    rvm1_rvm_check_for_updates: True
  roles:
  - rvm_io.rvm1-ruby

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  roles:
  - github-pages