---
- name: Wine | Install Wine and all Dependencies
  command: "{{ item }}" 
  sudo: yes
  with_items:
    - "dpkg --add-architecture i386"
    - "wget -nc https://dl.winehq.org/wine-builds/winehq.key"
    - "apt-key add winehq.key"
    - "apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/"
    - "apt update"
    - "apt-get install -y winehq-stable"
